// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATuMk0ve6egnc_Ge8GXQuQqGKkgGcOL0M',
    appId: '1:673118911922:web:293be50aeb5a5504f8b8ab',
    messagingSenderId: '673118911922',
    projectId: 'chat-app-fc2b5',
    authDomain: 'chat-app-fc2b5.firebaseapp.com',
    storageBucket: 'chat-app-fc2b5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEtSWyFM5Jh1PDuCqBFEl8brIkzVx_dm0',
    appId: '1:673118911922:android:6d0bb991a2f211d2f8b8ab',
    messagingSenderId: '673118911922',
    projectId: 'chat-app-fc2b5',
    storageBucket: 'chat-app-fc2b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlERWmDygjqddqbyUjfRXDFAUS7qXYhXo',
    appId: '1:673118911922:ios:cc0521339cd77e4ef8b8ab',
    messagingSenderId: '673118911922',
    projectId: 'chat-app-fc2b5',
    storageBucket: 'chat-app-fc2b5.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlERWmDygjqddqbyUjfRXDFAUS7qXYhXo',
    appId: '1:673118911922:ios:cc0521339cd77e4ef8b8ab',
    messagingSenderId: '673118911922',
    projectId: 'chat-app-fc2b5',
    storageBucket: 'chat-app-fc2b5.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATuMk0ve6egnc_Ge8GXQuQqGKkgGcOL0M',
    appId: '1:673118911922:web:34dd81a66dc3deb2f8b8ab',
    messagingSenderId: '673118911922',
    projectId: 'chat-app-fc2b5',
    authDomain: 'chat-app-fc2b5.firebaseapp.com',
    storageBucket: 'chat-app-fc2b5.firebasestorage.app',
  );
}
